version: '3.4'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5673:5673"

    worker:
        build:
            context: .
            dockerfile: Dockerfile
            target: celery_worker

        # volumes:
            # - .:/app
        image: mucor3_worker
        # deploy:
          # resources:
              # limits:
                  # cpus: '4'
                  # memory: 4G
              # reservations:
                  # cpus: '2'
                  # memory: 500M
        links:
            - rabbit
        depends_on:
            - rabbit
        volumes:
            - data-volume:/data
    webapp:
        environment:
            - MODULE_NAME=mucor3_flask.app
        build:
            context: .
            dockerfile: Dockerfile
            target: flask
        image: mucor3_webapp
        ports:
            - "80:80"
        volumes:
            - data-volume:/data
volumes:
     data-volume: 
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/tmp'

