name: unittests
on: [push, pull_request]

jobs:
  linux-unittests:
    name: Dub Tests LDC
    strategy:
      matrix:
        os: [ubuntu-latest]
        dc: [dmd-latest, ldc-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install htslib deps
        run: |
            sudo apt-get update && sudo apt-get install -y build-essential autoconf zlib1g-dev libbz2-dev liblzma-dev libcurl4-openssl-dev libssl-dev

      - name: Cache htslib
        id: cache-htslib
        uses: actions/cache@v2
        with:
          path: htslib-1.15.1
          key: ${{ runner.os}}-htslib-1.15.1

      - name: Build htslib
        if: steps.cache-htslib.outputs.cache-hit != 'true'
        run: |
            wget https://github.com/samtools/htslib/releases/download/1.15.1/htslib-1.15.1.tar.bz2
            tar -xf htslib-1.15.1.tar.bz2
            cd htslib-1.15.1
            autoreconf -i
            ./configure
            make

      - name: Install htslib
        run: |
            cd htslib-1.15.1
            sudo make install
            sudo ldconfig

      - name: Run tests
        run: dub -q test -b=unittest-cov
        env:
          LIBRARY_PATH: /usr/local/lib

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)